# Refer to https://github.com/probe-rs/cargo-embed/blob/master/src/config/default.toml
# for the comprehensive list of options

[default.general]
chip = "STM32F042G6Ux"

[default.rtt]
enabled = true
show_timestamps = true
